version: '3'

services:
    postgres:
        build: ./postgres
        container_name: postgres
        ports:
            - 2345:5432
        networks:
            - sql
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    
    mongo:
        build: ./mongo
        container_name: mongo
        ports:
            - 27017:27017
        networks:
            - nosql
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: passwd
            MONGO_INITDB_DATABASE: healthsystem 
          
    flask:
        build: ./flask
        container_name: flask
        ports:
            - 5000:5000
        networks:
            - sql
            - nosql
            - web
        environment:
            - FLASK_APP=flaskr
            - FLASK_ENV=development
        depends_on:
            - mongo
            - postgres
        links:
            - mongo
            - postgres
        command: gunicorn flaskr:app -b 0.0.0.0:5000

    nginx:
        build: ./nginx
        container_name: nginx
        ports:
            - 80:80
        networks:
            - web
        depends_on:
            - flask
        links:
            - flask

networks:
    sql:
    nosql:
    web:
