version: '2'

services:
    postgres:
        build: ./postgres
        container_name: postgres
        ports:
            - 2345:5432
        networks:
            - net
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    
    flask:
        build: ./flask
        container_name: flask
        volumes:
            - ./flask:/usr/src/app
        ports:
                - 5001:5000
        networks:
            - net
        environment:
            - FLASK_APP=flaskr
            - FLASK_ENV=development
            - FLASK_RUN_HOST=0.0.0.0
        depends_on:
            - postgres
        links:
            - postgres
        command: flask run
    mongo:
        build: ./mongo
        container_name: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: passwd
            MONGO_INITDB_DATABASE: healthsystem
volumes:
    postgres:
networks:
    net:
