--  Insert on table TIPO_DOC
--  DEFAULT is for serial id_tipo
insert into tipo_doc values (DEFAULT, 'passaporto');
insert into tipo_doc values (DEFAULT, 'carta di identita');

--  Insert on table INDIRIZZO
--  DEFAULT is for serial id_indirizzo
insert into indirizzo values (DEFAULT, '80121', 'Via Gaetani 22');
insert into indirizzo values (DEFAULT, '80127', 'Via Cilea 250');
insert into indirizzo values (DEFAULT, '80123', 'Via Alessandro Manzoni 141');
insert into indirizzo values (DEFAULT, '80127', 'Via A. Vaccaro 23');
insert into indirizzo values (DEFAULT, '80122', 'Viale M.C. Savoia 26');
insert into indirizzo values (DEFAULT, '80122', 'Via Francesco Petrarca 151');
insert into indirizzo values (DEFAULT, '80123', 'Via Posillipo 149');
insert into indirizzo values (DEFAULT, '80131', 'Via Nuova San Rocco 95');
insert into indirizzo values (DEFAULT, '80128', 'Via Antonio Pitloo 7');
insert into indirizzo values (DEFAULT, '80129', 'Via Suarez 38');
insert into indirizzo values (DEFAULT, '80122', 'Via Pontano 7');
insert into indirizzo values (DEFAULT, '80127', 'Via Raffaele Morghen 37');
insert into indirizzo values (DEFAULT, '80134', 'Via Toledo 429');
insert into indirizzo values (DEFAULT, '80138', 'Corso Umberto I 7');
insert into indirizzo values (DEFAULT, '80122', 'Corso Vittorio Emanuele 697');
insert into indirizzo values (DEFAULT, '80125', 'Viale Di Augusto 42');
insert into indirizzo values (DEFAULT, '80100', 'Via Giovanni Porzio Isola G1 4');
insert into indirizzo values (DEFAULT, '80135', 'Via Santa Teresa Degli Scalzi 8');
insert into indirizzo values (DEFAULT, '80129', 'Via Solimena 155');
insert into indirizzo values (DEFAULT, '80121', 'Via Chiaia 142');
insert into indirizzo values (DEFAULT, '80133', 'Via Ponte Di Tappia 82');
insert into indirizzo values (DEFAULT, '80132', 'Via S. Lucia 15');
insert into indirizzo values (DEFAULT, '80142', 'Piazza Garibaldi 26');
insert into indirizzo values (DEFAULT, '80129', 'Largo Francesco Celebrano 27');
insert into indirizzo values (DEFAULT, '80126', 'Via Servio Tullio');
insert into indirizzo values (DEFAULT, '80125', 'Via S. Veniero 17');
insert into indirizzo values (DEFAULT, '80129', E'Via D\'Auria 3');
insert into indirizzo values (DEFAULT, '80125', 'Via Giacomo Leopardi 90');
insert into indirizzo values (DEFAULT, '80137', 'Piazza Cavour 152');
insert into indirizzo values (DEFAULT, '80132', 'Via Santa Lucia 173');
insert into indirizzo values (DEFAULT, '80129', E'Piazza Dell\'Immacolata 26');
insert into indirizzo values (DEFAULT, '80129', 'Via Fiore 19');
insert into indirizzo values (DEFAULT, '80128', 'Via S. Giacomo Dei Capri 52');
insert into indirizzo values (DEFAULT, '80131', 'Via Bosco Capodimonte 101');
insert into indirizzo values (DEFAULT, '80131', 'Via Giovanni Miranda 8');
insert into indirizzo values (DEFAULT, '80121', 'Via G. Martucci 72');
insert into indirizzo values (DEFAULT, '80122', 'Viale Antonio Gramsci 20');
insert into indirizzo values (DEFAULT, '80131', 'Via Quagliariello 35');
insert into indirizzo values (DEFAULT, '80129', 'Via Gian Lorenzo Bernini 104');
insert into indirizzo values (DEFAULT, '80122', 'Via Mergellina 23');
insert into indirizzo values (DEFAULT, '80132', 'Via Santa Lucia 110');
insert into indirizzo values (DEFAULT, '80136', 'Via Salvator Rosa 245');
insert into indirizzo values (DEFAULT, '80136', 'Via Battistello Caracciolo 16');
insert into indirizzo values (DEFAULT, '80134', 'Via Cardinale Gugliemo Sanfelice 33');
insert into indirizzo values (DEFAULT, '80131', 'Via De Martino Augusto 7');
insert into indirizzo values (DEFAULT, '80124', E'Viale Cavalleggeri D\'Aosta 7');
insert into indirizzo values (DEFAULT, '80121', 'Via Cuoco 5');
insert into indirizzo values (DEFAULT, '80134', 'Via Toledo 329');
insert into indirizzo values (DEFAULT, '80122', 'Via Michelangelo Schipa 22');
insert into indirizzo values (DEFAULT, '80135', 'Via Broggia 18');
insert into indirizzo values (DEFAULT, '80134', 'Calata Trinita Maggiore 53');
insert into indirizzo values (DEFAULT, '80129', 'Via Torrione S. Martino 51');
insert into indirizzo values (DEFAULT, '80143', 'Corso Novara 40');
insert into indirizzo values (DEFAULT, '80122', 'Via Francesco Giordani 30');
insert into indirizzo values (DEFAULT, '80147', 'Via Provinciale Botteghelle di Portici 534');
insert into indirizzo values (DEFAULT, '80127', 'Via Aniello Falcone 386');
insert into indirizzo values (DEFAULT, '80131', 'Via Bosco Capodimonte 101');
insert into indirizzo values (DEFAULT, '80100', 'Via Salv. Rosa 146');
insert into indirizzo values (DEFAULT, '80127', 'Via Tasso 183');
insert into indirizzo values (DEFAULT, '80100', 'Via Renato Carosone 39');
insert into indirizzo values (DEFAULT, '80129', 'Via Kerbaker 8');
insert into indirizzo values (DEFAULT, '80133', 'Via Robeerto Bracco 71');
insert into indirizzo values (DEFAULT, '80127', 'Via Achille Vianelli 10');
insert into indirizzo values (DEFAULT, '80126', E'Via Dell\'Epomeo 219');
insert into indirizzo values (DEFAULT, '80144', 'Corso Secondigliano 166');
insert into indirizzo values (DEFAULT, '80126', 'Via Garzilli 59');
insert into indirizzo values (DEFAULT, '80137', 'Piazza Cavour 19');
insert into indirizzo values (DEFAULT, '80131', 'Via A. De Martino 7');
insert into indirizzo values (DEFAULT, '80129', 'Via G. Santacroce 5');
insert into indirizzo values (DEFAULT, '80129', 'Via S. Abate 33');
insert into indirizzo values (DEFAULT, '80138', 'Via Duomo 19');
insert into indirizzo values (DEFAULT, '80122', 'Via Arangio Ruiz 83');
insert into indirizzo values (DEFAULT, '80143', 'Via Rimini 67');
insert into indirizzo values (DEFAULT, '80129', 'Via Eduardo Suarez 16');
insert into indirizzo values (DEFAULT, '80129', 'Viale Michelangelo 13');
insert into indirizzo values (DEFAULT, '80128', E'Piazza Medaglie D\'Oro 27');
insert into indirizzo values (DEFAULT, '80122', 'Via Luca Da Penne 3');
insert into indirizzo values (DEFAULT, '80134', 'Via Toledo 373');

