version: '3'

services:
    postgres:
        build: ./postgresql
        container_name: postgres
        ports:
            - 2345:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
